baseURL = "https://sametkoyuncu.github.io/blog/"
title = "Samet Koyuncu"
theme = "github.com/adityatelange/hugo-PaperMod"
defaultContentLanguage = "tr"

[pagination]
  pagerSize = 10

disableKinds = ["taxonomy"]

[author]
  name = "Samet Koyuncu"

disablePathToLower = false
enableRobotsTXT = true
disableAliases = false

[minify]
  disableXML = false
  minifyOutput = true

[services]
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  page = ["HTML"]
  taxonomy = ["HTML", "RSS"]

[permalinks]
  posts = "/:section/:year/:month/:slug/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  env = "production"
  description = "Samet Koyuncu'nun Hugo PaperMod blogu"
  author = "Samet Koyuncu"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  defaultTheme = "auto"
  disableThemeToggle = false
  hideSummary = false
  comments = false

  [params.assets]
    favicon = "favicon.ico"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    apple_touch_icon = "apple-touch-icon.png"
    safari_pinned_tab = "safari-pinned-tab.svg"

  [params.label]
    text = "Samet Koyuncu"
    icon = ""
    iconHeight = 35


[languages]
  [languages.tr]
    languageName = "Türkçe"
    weight = 1
    contentDir = "content/tr"
    title = "Samet Koyuncu"
    languageCode = "tr-tr"
    [languages.tr.params]
      description = "Samet Koyuncu'nun Türkçe Hugo PaperMod blogu"
      [languages.tr.params.profileMode]
        enabled = true
        title = "Merhaba, ben Samet"
        subtitle = "iOS geliştiricisi ve teknoloji blog yazarı."
        imageUrl = "https://avatars.githubusercontent.com/u/17934179?s=400&u=abbb2903cb7385d77fc25f2bbb4ee2ffdea19131&v=4"
        imageTitle = "Samet Koyuncu"
        buttons = [
          { name = "Yazılar", url = "posts/" },
          { name = "GitHub", url = "https://github.com/sametkoyuncu" }
        ]
    [languages.tr.menu]
      [[languages.tr.menu.main]]
        identifier = "posts"
        name = "Yazılar"
        url = "posts/"
        weight = 10
  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
    title = "Samet Koyuncu"
    languageCode = "en-us"
    [languages.en.params]
      description = "Samet Koyuncu's English Hugo PaperMod blog"
      [languages.en.params.profileMode]
        enabled = true
        title = "Hi, I'm Samet"
        subtitle = "iOS developer sharing notes in English."
        imageUrl = "https://avatars.githubusercontent.com/u/17934179?s=400&u=abbb2903cb7385d77fc25f2bbb4ee2ffdea19131&v=4"
        imageTitle = "Samet Koyuncu"
        buttons = [
          { name = "Posts", url = "posts/" },
          { name = "GitHub", url = "https://github.com/sametkoyuncu" }
        ]
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "en/posts/"
        weight = 10

[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
